name: Linter

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install the code linting and formatting tool Ruff
      run: pip install ruff
    - name: Lint code with Ruff
      run: ruff check --output-format=github --target-version=py39
    - name: Check code formatting with Ruff
      run: ruff format --diff --target-version=py39
      continue-on-error: true
